var Connections = [
    { name: 'First names of dictators', data: ['Adolf', 'Joseph', 'Mao', 'Hideki'] },
    { name: 'Dog breeds', data: ['Beagle', 'Chihuahua', 'Shepard', 'Husky'] },
    { name: 'College/University', data: ['Yale', 'Harvard', 'MIT', 'Princeton'] },
    { name: 'Common first names', data: ['Steve', 'Muhammad', 'Rachael', 'John'] },
    { name: 'Months of the year', data: ['June', 'August', 'January', 'April'] },
    { name: 'States in the US', data: ['Florida', 'Wisconsin', 'Wyoming', 'Colorado'] },
    { name: 'Heavy metals', data: ['Lead', 'Chromium', 'Arsenic', 'Mercury'] },
    { name: 'Type of bread', data: ['Baguette', 'Bun', 'Loaf', 'Roll'] },
    { name: 'Small imperfection', data: ['Chip', 'Mark', 'Nick', 'Scratch'] },
    { name: 'Monthly bills', data: ['Cable', 'Electric', 'Gas', 'Water'] },
    { name: 'Related to sound', data: ['Acoustic', 'Auditory', 'Sonic', 'Heard'] },
    { name: 'Circular shapes', data: ['Band', 'Circle', 'Hoop', 'Ring'] },
    { name: 'Type of jam', data: ['NBA', 'Paper', 'Pearl', 'Traffic'] },
    { name: 'Places to shop', data: ['Mall', 'Market', 'Outlet', 'Store'] },
    { name: 'Ways to remove hair', data: ['Shave', 'Thread', 'Tweeze', 'Wax'] },
    { name: 'Types of wrenches', data: ['Allen', 'Crescent', 'Monkey', 'Wrench'] },
    { name: 'Avoid', data: ['Dodge', 'Duck', 'Escape', 'Skirt'] },
    { name: 'Types of cheese', data: ['Cottege', 'Cream', 'Mozzarella', 'String'] },
    { name: 'Types of insturment', data: ['Bass', 'Harp', 'Organ', 'Horn'] },
    { name: 'Dog commands', data: ['Come', 'Down', 'Sit', 'Stay'] },
    { name: 'Rooms in a house', data: ['Bedroom', 'Den', 'Kitchen', 'Basement'] },
    { name: 'Carry a tune', data: ['Hum', 'Sing', 'Whistle', 'Scat'] },
    { name: 'Whole amount', data: ['Count', 'Gross', 'Sum', 'Total'] },
    { name: 'Things that are sticky', data: ['Glue', 'Gum', 'Tape', 'Stick'] },
    { name: 'Financial terms', data: ['Capital', 'Equity', 'Interest', 'Stock'] },
    { name: 'Secluded', data: ['Hidden', 'Private', 'Remote', 'Secret'] },
    { name: 'Aggregate Size', data: ['Amount', 'Number', 'Quanity', 'Volume'] },
    { name: 'Bodies of water', data: ['Canal', 'Channel', 'Sound', 'Strait'] },
    { name: 'Criticize', data: ['Knock', 'Pan', 'Roast', 'Pan'] },
    { name: 'Reality shows', data: ['Alone', 'Catfish', 'Chopped', 'Survivor'] },
    { name: 'Foods with crusts', data: ['Pasty', 'Pie', 'Tart', 'Turnover'] },
    { name: 'Ending with a silent T', data: ['Bouquet', 'Parfait', 'Ragout', 'Rapport'] },
    { name: 'Countries with red and white flags', data: ['Japan', 'Poland', 'Tunisia', 'Turkey'] },
    { name: 'Famous NBA players', data: ['Bird', 'Curry', 'James', 'Jordan'] },
    { name: 'Areas between mountains', data: ['Canyon', 'Glutch', 'Pass', 'Ravine'] },
    { name: 'Eat', data: ['Gorge', 'Gulp', 'Scarf', 'Wolf'] },
    { name: 'Featured in snow white', data: ['Apple', 'Bashful', 'Mirror', 'Queen'] },
    { name: 'Type of bird starting with a C', data: ['Chen', 'Clark', 'Cowl', 'Craven'] },
    { name: 'Types of teeth', data: ['Canine', 'Fang', 'K9', 'Tusk'] },
    { name: 'Fashionable', data: ['Chic', 'Hip', 'Hot', 'In'] },
    { name: 'Dance moves', data: ['Floss', 'Robot', 'Vogue', 'Worm'] },
    { name: 'Things that suck', data: ['Leech', 'Straw', 'Vacuum', 'Vampire'] },
    { name: 'Religious figures', data: ['Cardinal', 'Lama', 'Monk', 'Pastor'] },
    { name: 'Primates', data: ['Baboon', 'Gorilla', 'Bonobo', 'Gibbon'] },
    { name: 'Onset', data: ['Birth', 'Creation', 'Dawn', 'Start'] },
    { name: 'Walk', data: ['March', 'Step', 'Stride', 'Thread'] },
    { name: 'Holiday', data: ['Earth', 'Groundhog', 'Labor', 'Christmas'] },
    { name: 'Quick peak', data: ['Gander', 'Glance', 'Glimpse', 'Look'] },
    { name: 'Parts of a mountain', data: ['Cliff', 'Crag', 'Ledge', 'Ridge'] },
    { name: 'Bodyweight exercises', data: ['Dips', 'Lunges', 'Planks', 'Squats'] },
    { name: 'Email sign-offs', data: ['Best', 'Cheers', 'Regards', 'Thanks'] },
    { name: 'Short form for MLB teams', data: ['Cards', 'Jays', 'Nets', 'Yanks'] },
    { name: 'Elizabeths', data: ['Banks', 'Moss', 'Tayor', 'Warren'] },
    { name: 'Great ____', data: ['Dane', 'Lake', 'Seal', 'White'] },
    { name: 'Gross', data: ['Ew', 'Ick', 'PU', 'Ugh'] },
    { name: '"Yes" in different languages', data: ['Hai', 'Ja', 'Si', 'Da'] },
    { name: 'Homophones', data: ['Oui', 'We', 'Wee', 'Wii'] },
    { name: 'Basic emotions', data: ['Anger', 'Fear', 'Happiness', 'Suprise'] },
    { name: 'Obtain', data: ['Get', 'Land', 'Secure', 'Win'] },
    { name: 'Ant', data: ['Adam', 'Carpenter', 'Fire', 'Red'] },
    { name: 'Unit of language', data: ['Letter', 'Paragraph', 'Sentence', 'Word'] },
    { name: 'Trademark', data: ['Feature', 'Hallmark', 'Stamp', 'Trait'] },
    { name: 'Funny person', data: ['Card', 'Clown', 'Cutup', 'Joker'] },
    { name: 'Things with leaves', data: ['Book', 'Table', 'Tea', 'Tree'] },
    { name: 'Presidents', data: ['Ford', 'Grant', 'Lincoln', 'Wilson'] },
    { name: 'Car companies', data: ['BMW', 'Honda', 'Jaguar', 'Subaru'] },
    { name: 'Common prefixes', data: ['Auto', 'Post', 'Semu', 'Sub'] },
    { name: 'Sparse/Lacking', data: ['Light', 'Short', 'Spare', 'Thin'] },
    { name: 'Spices', data: ['Anise', 'Dill', 'Nutmeg', 'Sage'] },
    { name: 'Intelligent', data: ['Bright', 'Quick', 'Smart', 'Intelligent'] },
    { name: 'Deoderant', data: ['Axe', 'Degree', 'Old Spice', 'Native'] },
    { name: 'Medival weapons', data: ['Club', 'Mace', 'Spear', 'Sword'] },
    { name: 'Doctors orders', data: ['Diet', 'Exercise', 'Fresh air', 'Sleep'] },
    { name: 'Email actions', data: ['Compose', 'Forward', 'Reply All', 'Send'] },
    { name: 'Podcasts', data: ['Joe Rogan', 'Up First', 'Radiolab', 'WTF'] },
    { name: '___ Comedy', data: ['Black', 'Divine', 'Prop', 'Sketch'] },
    { name: 'Brought to the beach', data: ['Flip-Flop', 'Sunscreen', 'Towel', 'Umbrella'] },
    { name: 'Types of french fries', data: ['Curly', 'Shoestring', 'Waffle', 'Wedge'] },
    { name: 'Notification sounds', data: ['Chime', 'Ding', 'Ping', 'Ring'] },
    { name: 'Tattle', data: ['Rat', 'Snitch', 'Sing', 'Squeal'] },
    { name: 'Microsoft products', data: ['Edge', 'Surface', 'Word', 'Bing'] },
    { name: 'Google products', data: ['Search', 'Maps', 'Earth', 'Images'] },
    { name: 'Investments', data: ['Bond', 'Option', 'Stock', 'Crypto'] },
    { name: 'Terms for records', data: ['LP', 'Platter', 'Vinyl', 'Wax'] },
    { name: 'Cube Shaped', data: ['Ice', 'Die', 'Sugar', 'Bouillon'] },
    { name: 'Unchanging', data: ['Even', 'Level', 'Stable', 'Steady'] },
    { name: 'Long/Sharp', data: ['Lance', 'Pin', 'Skewer', 'Spit'] },
    { name: 'Music publications', data: ['Billboard', 'Pitchfork', 'Rolling Stone', 'Spit'] },
    { name: 'Ways to prepare', data: ['Drill', 'Practice', 'Study', 'Train'] },
    { name: 'Hollow cylinders', data: ['Hose', 'Pipe', 'Straw', 'Tube'] },
    { name: 'Ignite', data: ['Burn', 'Kindle', 'Light', 'Torch'] },
    { name: 'Information', data: ['Data', 'Info', 'Intel', 'News'] },
    { name: 'Small wooded area', data: ['Dell', 'Glen', 'Hollow', 'Valley'] },
    { name: 'Things with cores', data: ['Apple', 'Planet', 'Computer', 'Reactor'] },
    { name: 'Social media actions', data: ['Like', 'Subscribe', 'Share', 'Follow'] },
    { name: 'Expressions of hesitation', data: ['Erm', 'Uh', 'Um', 'Well'] },
    { name: 'Flowers', data: ['Daisy', 'Rose', 'Tulip', 'Violet'] },
    { name: 'Seen on a farm', data: ['Barn', 'Chicken', 'Farmer', 'Tractor'] },
    { name: 'Bird features', data: ['Beak', 'Feather', 'Talon', 'Wing'] },
    { name: 'Senses', data: ['Sight', 'Smell', 'Taste', 'Touch'] },
    { name: 'Space missions', data: ['Apollo', 'Discovery', 'Endeavour', 'Voyager'] },
    { name: 'Different breeds of dogs', data: ['Husky', 'Poodle', 'Retriever', 'Terrier'] },
    { name: 'Ocean creatures', data: ['Dolphin', 'Jellyfish', 'Shark', 'Whale'] },
    { name: 'Programming languages', data: ['Java', 'Python', 'Ruby', 'Swift'] },
    { name: 'Weather phenomena', data: ['Rainbow', 'Tornado', 'Thunderstorm', 'Hurricane'] },
    { name: 'Elements on the periodic table', data: ['Carbon', 'Helium', 'Oxygen', 'Gold'] },
    { name: 'Movie genres', data: ['Action', 'Comedy', 'Horror', 'Sci-Fi'] },
    { name: 'Types of cuisine', data: ['Italian', 'Japanese', 'Mexican', 'Thai'] },
    { name: 'Famous bridges', data: ['Golden Gate', 'Brooklyn', 'Tower Bridge', 'Sydney Harbour'] },
    { name: 'Planets in the solar system', data: ['Mars', 'Neptune', 'Saturn', 'Uranus'] },
    { name: 'Board games', data: ['Chess', 'Monopoly', 'Scrabble', 'Risk'] },
    { name: 'Art movements', data: ['Cubism', 'Impressionism', 'Surrealism', 'Renaissance'] },
    { name: 'Major world religions', data: ['Christianity', 'Islam', 'Buddhism', 'Hinduism'] },
    { name: 'Types of tea', data: ['Green', 'Black', 'Oolong', 'Herbal'] },
    { name: 'Different cloud types', data: ['Cumulus', 'Cirrus', 'Stratus', 'Nimbostratus'] } ,
    { name: 'Different races', data: ['Asian', 'Nascar', 'Speedway', 'Karting'] },
  ];  