"use strict";
const Projects = new Page('projects', Content.element);
const Featured = new FlexGlassPane(Projects.element, CSS_FullWidthFitHeight);
new TextHeader(Featured.element, 'Featured');
const FeaturedScroll = new ScrollGlassPane('x', Featured.element, { width: '100%', height: '260px' });
const FeaturedList = new ProjectList(FeaturedScroll.element);
FeaturedList.createProjectList(Project_Data, null, true);
const Apps = new GlassPane(Projects.element, CSS_FullWidthFitHeight);
new TextHeader(Apps.element, 'Apps');
const AppList = new ProjectHolderGlassPane('app', Apps.element);
const Games = new GlassPane(Projects.element, CSS_FullWidthFitHeight);
new TextHeader(Games.element, 'Games');
const GameList = new ProjectHolderGlassPane('game', Games.element);
